services:
  db:
    image: "postgres:17"
    container_name: ecom-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ecom_postgres_data:/var/lib/postgresql/data
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:7-alpine"
    container_name: ecom-redis
    ports:
      - "6380:6379"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: "redis/redisinsight:latest"
    container_name: ecom-redisinsight
    ports:
      - "5541:5540"
    networks:
      - ecom-network
    depends_on:
      - redis

volumes:
  ecom_postgres_data:
    driver: local

networks:
  ecom-network:
